LICENSE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/2)

Add valid LICENSE file.

---

src/tests/CMakeLists.txt
src/tests/pmempools/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/7)

common: fix license text mismatches with LICENSE file

---

src/tests/CMakeLists.txt
src/tests/pmempools/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/8)

common: fix date in lincense

---

README.md
etc/scripts/run_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/6)

scripts: switch to python 3.4

---

etc/scripts/download_file.ps1
functions.cmake

Now downloading googletest ang pugixml will be done only if necessary.
Also the file is verified by powershell script which means that it will be done again if checksum is incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/3)

powershell - download file only if necessary, add checksum verification

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/16)

common: CMake - fix variable names on Windows

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/12)

common: add contribution instruction

---

src/tests/pmemobj/CMakeLists.txt
src/tests/pmemobj/main.cc
src/tests/pmemobj/obj_ctl/alloc_class/alloc_class.cc
src/tests/pmemobj/obj_ctl/alloc_class/alloc_class.h
src/tests/pmemobj/obj_ctl/alloc_class/alloc_class_test.cc
src/tests/pmemobj/obj_ctl/alloc_class/alloc_class_utils.cc
src/tests/pmemobj/obj_ctl/alloc_class/alloc_class_utils.h
src/tests/pmemobj/obj_ctl/alloc_class/ext_cfg.cc
src/tests/pmemobj/obj_ctl/alloc_class/ext_cfg.h
src/tests/pmemobj/obj_ctl/alloc_class/ext_cfg_test.cc
src/utils/api_c/api_c.h
src/utils/api_c/linux_api.cc
src/utils/api_c/windows_api.cc

Tests for obj_ctl: allocation classes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/17)

obj_ctl: alloc class tests

---

etc/jenkins/README
etc/jenkins/pmdk_cpp_tests
etc/jenkins/pmdk_drd_tests
etc/jenkins/pmdk_helgrind_tests
etc/jenkins/pmdk_long_tests
etc/jenkins/pmdk_memcheck_tests
etc/jenkins/pmdk_pmemcheck_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/22)

common: add jenkins pipeline jobs

---

src/tests/pmempools/pmempool_create/pmempool_create.h
src/tests/pmempools/utils/structures.h
src/utils/api_c/api_c.cc
src/utils/api_c/api_c.h
src/utils/api_c/linux_api.cc
src/utils/api_c/windows_api.cc
src/utils/configXML/local_configuration.h
src/utils/configXML/read_config.h
src/utils/non_copyable/non_copyable.h
src/utils/output/output.h
src/utils/poolset/part.h
src/utils/poolset/poolset.h
src/utils/poolset/replica.h
src/utils/shell/i_shell.h
src/utils/string_utils.h
src/utils/test_utils/file_utils.h

Added descriptions for utils / pmempool utils / pmempool create tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/5)

Add descriptions

---

src/utils/api_c/api_c.h
src/utils/api_c/windows_api.cc
src/utils/shell/i_shell.h
src/utils/shell/windows_shell.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/14)

add Unicode support

---

etc/jenkins/pmdk_cpp_tests
etc/jenkins/pmdk_drd_tests
etc/jenkins/pmdk_helgrind_tests
etc/jenkins/pmdk_long_tests
etc/jenkins/pmdk_memcheck_tests
etc/jenkins/pmdk_pmemcheck_tests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/26)

common: add timestamps

---

etc/scripts/download_file.ps1

SSL certificate wasn't properly created/used after recent changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/29)

scripts: fixing issues with downloading gtest

---

README.md
etc/config/README.md
etc/config/config.xml.example
src/tests/ras/CMakeLists.txt
src/tests/ras/main.cc
src/tests/ras/utils/configXML/dimm_configuration.cc
src/tests/ras/utils/configXML/dimm_configuration.h
src/tests/ras/utils/configXML/local_dimm_configuration.cc
src/tests/ras/utils/configXML/local_dimm_configuration.h
src/tests/ras/utils/configXML/remote_dimm_configuration.cc
src/tests/ras/utils/configXML/remote_dimm_configuration.h
src/utils/api_c/api_c.cc
src/utils/api_c/linux_api.cc
src/utils/api_c/windows_api.cc
src/utils/configXML/local_configuration.cc
src/utils/configXML/read_config.h
src/utils/configXML/remote_configuration.cc
src/utils/configXML/remote_configuration.h
src/utils/constants.h

Added reading:
- dimm configuration
- remote configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/24)

utils: reading config file

---

src/tests/pmempools/pmempool_create/invalid_arguments_tests.cc
src/tests/pmempools/pmempool_create/valid_arguments_tests.cc
src/utils/poolset/poolset.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/33)

utils/pmempools: fix for hardcoded configuration

---

src/tests/scripts/test_build_rpm_packages.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/28)

scripts: add python script which check completeness of build of rpm packages

---

src/tests/scripts/split_manpage/split_manpage_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/36)

scripts: add function 'parse_argument' and add optional argument 'PMDK_doc_path"

---

.clang-format

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/39)

common: add clang-format file

---

etc/config/config.xml.example
src/tests/ras/utils/ras_configXML/ras_configuration.cc
src/tests/ras/utils/ras_configXML/ras_configuration.h
src/utils/shell/i_shell.h

functionality for supporting power cycles from external machine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/38)

remote ras support

---

src/tests/pmempools/pmempool_create/invalid_arguments_tests.cc
src/tests/pmempools/pmempool_create/pmempool_create_tests_CLI.cc

Changed expected message in two TC's
Removed checking output from help message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/40)

pmempools: changed expected message

---

src/tests/ras/utils/rebooters/powerswitch/powerswitch.py
src/tests/ras/utils/rebooters/powerswitch/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/37)

scripts: add script to manage remote powerswitch

---

src/tests/scripts/split_manpage/exceptions.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/43)

scripts: Add 'pmemvlt' to exceptions.txt in the script which tests man page.

---

src/tests/scripts/test_rpm_packages_installation.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/42)

scripts: add a script which checks the correctness of installation of rpm packages

---

.gitignore
CMakeLists.txt
etc/scripts/check_format.py
etc/scripts/check_license.py
etc/scripts/check_utils.py
src/tests/pmemobj/main.cc
src/tests/pmemobj/obj_ctl/alloc_class/ext_cfg_test.cc
src/tests/pmempools/utils/structures.h
src/tests/ras/unsafe_shutdown/us_basic_tests.cc
src/tests/ras/unsafe_shutdown/us_local_replicas_tests.cc
src/tests/ras/utils/configXML/remote_dimm_configuration.cc
src/utils/api_c/api_c.h
src/utils/api_c/linux_api.cc
src/utils/api_c/windows_api.cc
src/utils/configXML/local_configuration.h
src/utils/configXML/read_config.h
src/utils/configXML/remote_configuration.h
src/utils/output/output.h
src/utils/poolset/part.h
src/utils/poolset/replica.cc
src/utils/shell/windows_shell.cc
src/utils/test_utils/file_utils.h
style-format.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/46)

Code style and license checks using Python and CMake - continue

---

src/tests/ras/unsafe_shutdown/unsafe_shutdown.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/52)

fix -Wnarrowing for pmempool_check_args flag

---

etc/config/config.xml.example
src/tests/ras/us_test_controller/ras_configuration.cc
src/tests/ras/us_test_controller/ras_configuration.h
src/tests/ras/us_test_controller/us_test_controller.cc
src/tests/ras/utils/inject_mananger/inject_manager.h
src/tests/ras/utils/inject_mananger/inject_manager_linux.cc
src/tests/ras/utils/test_phase/test_phase.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/49)

Align test controller logic to changes in USC tests

---

src/tests/pmemobj/obj_ctl/alloc_class/ext_cfg_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/56)

pmemobj: move the negative test case to positive test cases.

---

src/tests/scripts/test_build_rpm_packages.py
src/tests/scripts/test_rpm_packages_installation.py

I deleted elements associated with c++ and I test new tools from PMDK repository
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/54)

tests: Fix scripts testing rpm packages

---

src/tests/scripts/test_compile_public_headers.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/59)

scripts: add proper PMDK headers compilation test

---

src/tests/pmempools/pmempool_create/pmempool_create_tests_CLI.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/60)

tests: fix the test PMEMPOOL_CREATE_MAX_SIZE

---

src/tests/pmempools/pmempool_create/invalid_arguments_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/62)

Fix expected error output for pmempool test

---

src/tests/ras/utils/rebooters/powerswitch/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/63)

update urlib3 to 1.24.2

---

src/tests/scripts/split_manpage/exceptions.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/66)

scripts: Add 'pmdk_use_attr_deprec_with_msg' to exceptions.txt

---

src/tests/scripts/split_manpage/exceptions.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/67)

scripts: Add 'pobj_flag_no_snapshot' and 'pobj_xadd_no_snapshot' to exceptions.txt

---

src/tests/scripts/test_build_rpm_packages.py

In PMDK appeared a new experimental library: libpmem2 and the script required changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/75)

test: fix the script to test rpm packages

---

src/tests/ras/unsafe_shutdown/remote_replicas_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/76)

test: fix pool name in RAS test

---

src/tests/scripts/split_manpage/exceptions.txt
src/tests/scripts/split_manpage/split_manpage_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/74)

Test: fix doc tests

---

src/tests/ras/unsafe_shutdown/local_replicas_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/77)

ras: adjust pmempool check return code

---

src/tests/ras/unsafe_shutdown/remote_replicas_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/78)

ras: pool is syncable

---

src/tests/scripts/split_manpage/split_manpage_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/80)

tests: add an exception for Windows specific function in doc test

---

src/tests/scripts/split_manpage/split_manpage_tests.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmdk-tests/82)

Fix for manpage test

---

CMakeLists.txt

Added  "-Wno-deprecated-declarations" flag to CMakeList.txt file to fix compiling pmdk-tests repository

Added deprecated ignore flag

---

src/tests/ras/utils/rebooters/powerswitch/requirements.txt

https://github.com/pmem/pmdk-tests/security/dependabot/16

upgrade requests to fix Dependabot alert
